modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Evoslab/Mobful-Bricks/issues"
[[mods]]
modId="mobful_bricks"
version="1.0.0"
displayName="Mobful Bricks"
logoFile="mobful_bricks.png"
credits="Evo, EltrutLikes, Audako"
authors="Evo's Lab"
description='''
Mobful Bricks
'''

[[dependencies.mobful_bricks]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mobful_bricks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mobful_bricks]]
 modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"